# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  username: root
  host: 127.0.0.1
  database: rd_radio_development

test:
  adapter: mysql
  username: root
  host: 127.0.0.1
  database: rd_radio_test

